# Generated by Django 2.0.5 on 2018-05-13 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='name')),
                ('description', models.TextField(max_length=600, verbose_name='description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modification date')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price')),
                ('cook_time', models.CharField(max_length=3, verbose_name='cook time [h]')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='vegetarian dishes?')),
                ('image', models.ImageField(upload_to='dishes/', verbose_name='image')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menu.Menu', verbose_name='menu cards')),
            ],
            options={
                'verbose_name': 'dishes',
                'verbose_name_plural': 'dishes',
            },
        ),
    ]
