# Generated by Django 2.0.5 on 2018-05-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_auto_20180513_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='is_vegetarian',
            field=models.BooleanField(default=False, verbose_name='vegetarian dishes?'),
        ),
    ]
